Repository nightscout/Trio, pull requests merged in 2024-05, with the labels that each got.

#235 Enable editing of preset profile overrides
  FreeAPS/Sources/Modules/OverrideProfilesConfig/OverrideProfilesStateModel.swift
  FreeAPS/Sources/Modules/OverrideProfilesConfig/View/OverrideProfilesRootView.swift
Labels: enhancement

#236 Enable editing of preset temp targets
  FreeAPS/Sources/Modules/AddTempTarget/AddTempTargetStateModel.swift
  FreeAPS/Sources/Modules/AddTempTarget/View/AddTempTargetRootView.swift
Labels: enhancement

#202 Update(issue templates): More readable styling and expansion of questions
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: documentation

#249 Remove unused Import Settings in JSON that cause errors decoding JSON
  FreeAPS/Sources/Models/RawFetchedProfile.swift
  FreeAPS/Sources/Modules/NightscoutConfig/NightscoutConfigStateModel.swift
Labels: pending review
