Repository nightscout/Trio, pull requests merged in 2024-06, with the labels that each got.

#253 Set median of lower and upper correction range bound when importing L…
  FreeAPS/Sources/Modules/NightscoutConfig/NightscoutConfigStateModel.swift
Labels: enhancement

#266 Migrate fix for PumpManager: Use pump limit from pumpManager instead of UI
  FreeAPS/Sources/Modules/PumpSettingsEditor/PumpSettingsEditorProvider.swift
  FreeAPS/Sources/Modules/PumpSettingsEditor/PumpSettingsEditorStateModel.swift
Labels: pending review

#277 Port over pump loss fix via LoopKit/Loop#1702
  FreeAPS/Sources/APS/DeviceDataManager.swift
  FreeAPS/Sources/APS/Extensions/PumpManagerExtensions.swift
  FreeAPS/Sources/APS/Extensions/UserDefaultsExtensions.swift
  FreeAPS/Sources/APS/FetchGlucoseManager.swift
  FreeAPS/Sources/Helpers/PropertyWrappers/PersistedProperty.swift
  FreeAPS/Sources/Modules/Settings/SettingsStateModel.swift
  FreeAPS/Sources/Modules/Settings/View/SettingsRootView.swift
Labels: bug, pending review

#279 Merge alpha into dev
  FreeAPS/Resources/json/defaults/freeaps/freeaps_settings.json
  FreeAPS/Sources/APS/DeviceDataManager.swift
  FreeAPS/Sources/APS/Extensions/PumpManagerExtensions.swift
  FreeAPS/Sources/APS/Extensions/UserDefaultsExtensions.swift
  FreeAPS/Sources/APS/FetchGlucoseManager.swift
  FreeAPS/Sources/APS/Storage/CarbsStorage.swift
  FreeAPS/Sources/APS/Storage/PumpHistoryStorage.swift
  FreeAPS/Sources/Helpers/PropertyWrappers/PersistedProperty.swift
  FreeAPS/Sources/Models/FreeAPSSettings.swift
  FreeAPS/Sources/Models/PumpHistoryEvent.swift
  FreeAPS/Sources/Modules/PreferencesEditor/PreferencesEditorDataFlow.swift
  FreeAPS/Sources/Modules/PumpSettingsEditor/PumpSettingsEditorProvider.swift
  FreeAPS/Sources/Modules/PumpSettingsEditor/PumpSettingsEditorStateModel.swift
  FreeAPS/Sources/Modules/Settings/SettingsStateModel.swift
  FreeAPS/Sources/Modules/Settings/View/SettingsRootView.swift
  FreeAPS/Sources/Modules/WatchConfig/View/WatchConfigRootView.swift
  FreeAPS/Sources/Modules/WatchConfig/WatchConfigStateModel.swift
  FreeAPS/Sources/Services/WatchManager/WatchManager.swift
  FreeAPSWatch WatchKit Extension/DataFlow.swift
  FreeAPSWatch WatchKit Extension/Views/BolusConfirmationView.swift
  FreeAPSWatch WatchKit Extension/WatchStateModel.swift
Labels: Pre 1.0

#190 Auto-remove trailing slash from Nightscout URL
  FreeAPS/Sources/Modules/NightscoutConfig/NightscoutConfigStateModel.swift
Labels: Pre 1.0

#282 Fix the dexcom share in Trio
  FreeAPS/Sources/APS/CGM/PluginSource.swift
Labels: Pre 1.0

#299 testflight.md: Add the optional instructions for modifying automated build and sync
  fastlane/testflight.md
Labels: documentation
